### ISSUE TITLE
Cartridge deployment fails on OSE due to exceeding quota in JDK 8 deployment

### ISSUE THREAD

**Issue by vinnielima** [openshift-cartridges/openshift-wildfly-cartridge#35]
The cartridge fails to deploy on a node for a user due to JDK download.  While the install script has conditional statement to handle failed download, it does not handle inability to finish a download.  

Below is the extract from the failed cartridge deployment attempt:

>  Shell command '/sbin/runuser -s /bin/sh vinnie-jbosswildfly-1 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c5,c502' /bin/sh -c \"/var/lib/openshift/vinnie-jbosswildfly-1/wildfly/bin/install --version 8\""' returned an error. rc=2
> added manifest
> adding: WEB-INF/(in = 0) (out= 0)(stored 0%)
> adding: WEB-INF/web.xml(in = 353) (out= 186)(deflated 47%)
> adding: images/(in = 0) (out= 0)(stored 0%)
> adding: images/jbosscorp_logo.png(in = 1914) (out= 1919)(deflated 0%)
> adding: index.html(in = 41708) (out= 16433)(deflated 60%)
> adding: snoop.jsp(in = 5112) (out= 1258)(deflated 75%)
> WildFly 8 administrator added.  Please make note of these credentials:

>   Username: *******
>   Password: *********
   
>   run 'rhc port-forward jbosswildfly' to access the web admin area on port 9990.
> --2015-03-04 14:37:35--  http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-i586.tar.gz
> Resolving download.oracle.com... 23.67.251.57, 23.67.251.50
> .....
> tar: jdk1.8.0_05/lib/missioncontrol/plugins/org.eclipse.core.contenttype_3.4.200.v20120523-2004.jar: Wrote only 1536 of 10240 bytes
> tar: jdk1.8.0_05/lib/missioncontrol/plugins/org.eclipse.equinox.launcher.gtk.linux.x86.nl_zh_4.2.0.v20130724060447.jar: Cannot write: Disk quota exceeded

**Comment by fjuma** [comment]
The WildFly cartridge will actually be updated soon to no longer install JDK 8 during instance creation since JDK 8 is now available on OpenShift Online nodes.

**Comment by vinnielima** [comment]
This is more related to OSE 2 which currently does not have JDK 8.

**Comment by fjuma** [comment]
The WildFly cartridge has now been updated to no longer install JDK 8 during instance creation since this is no longer necessary for us. However, note that the cartridge does still use JDK 8 by default. The java7 marker can still be used for apps that require JDK 7. (If the cartridge is not being deployed on OpenShift Online and JDK 8 isn't available, one option is to create a git repository with the java7 marker file included and specify this git repository when creating the app. Alternatively, see https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Deployment_Guide/chap-Customizing_OpenShift_Enterprise.html#Creating_an_Application_Template for information about customizing application templates on OpenShift Enterprise.)
